export interface SeedGame {
  title: string;
  slug: string;
  category: string;
  thumbnail: string;
  iframeUrl: string;
  rating: number;
  playCount: number;
  description: string;
  featured: boolean;
  tags: string[];
}

// Real GameDistribution game (verified UUID hashes)
const gd = (hash: string) => ({
  thumbnail: `https://img.gamedistribution.com/${hash}-512x384.jpeg`,
  iframeUrl: `https://html5.gamedistribution.com/${hash}/`,
});

// CrazyGames embed — uses direct CDN URL to bypass Cloudflare domain checks
const cg = (slug: string) => ({
  thumbnail: `https://imgs.crazygames.com/games/${slug}/cover_16x9-1.png`,
  iframeUrl: `https://games.crazygames.com/en_US/${slug}/index.html`,
});

export const seedGames: SeedGame[] = [
  // ===== ACTION (13 games) =====
  {
    title: 'Temple Run 2',
    slug: 'temple-run-2',
    category: 'Action',
    ...cg('temple-run-2'),
    rating: 4.4,
    playCount: 510000,
    description: 'Run, jump, slide, and swipe through ancient temples. Navigate treacherous cliffs, zip lines, and mines to escape with the cursed idol.',
    featured: true,
    tags: ['endless-runner', 'action', 'adventure', 'running'],
  },
  {
    title: 'Eggy Car',
    slug: 'eggy-car',
    category: 'Action',
    ...cg('eggy-car'),
    rating: 4.5,
    playCount: 370000,
    description: 'Drive a car with an egg on top over crazy hills without dropping it. Hilarious physics-based challenge!',
    featured: false,
    tags: ['physics', 'driving', 'casual', 'funny'],
  },
  {
    title: 'Subway Surfers',
    slug: 'subway-surfers',
    category: 'Action',
    ...cg('subway-surfers'),
    rating: 4.8,
    playCount: 680000,
    description: 'Dash through the subway dodging oncoming trains. Swipe to turn, jump, and slide in this classic endless runner.',
    featured: true,
    tags: ['endless-runner', 'action', 'running', 'casual'],
  },
  {
    title: 'Vex 7',
    slug: 'vex-7',
    category: 'Action',
    ...cg('vex-7'),
    rating: 4.6,
    playCount: 420000,
    description: 'Navigate your stickman through deadly obstacle courses. Wall jump, slide and swim through increasingly difficult levels.',
    featured: true,
    tags: ['platformer', 'stickman', 'obstacle', 'challenging'],
  },
  {
    title: 'Iron Snout',
    slug: 'iron-snout',
    category: 'Action',
    ...cg('iron-snout'),
    rating: 4.4,
    playCount: 230000,
    description: 'Play as a tough piggy fighting off wolves. Punch, kick, and use their own weapons in this hilarious fighting game.',
    featured: false,
    tags: ['fighting', 'funny', 'action', 'casual'],
  },
  {
    title: 'Doodle Jump',
    slug: 'doodle-jump',
    category: 'Action',
    ...cg('doodle-jump'),
    rating: 4.2,
    playCount: 310000,
    description: 'Guide the Doodler up a sheet of graph paper, bouncing from platform to platform. Watch out for monsters!',
    featured: false,
    tags: ['jumping', 'casual', 'classic', 'arcade'],
  },
  {
    title: 'Rooftop Snipers',
    slug: 'rooftop-snipers',
    category: 'Action',
    ...cg('rooftop-snipers'),
    rating: 4.3,
    playCount: 275000,
    description: 'Battle on rooftops in this physics-based two-player shooting game. Knock your opponent off the roof to win!',
    featured: false,
    tags: ['2-player', 'shooting', 'physics', 'funny'],
  },
  {
    title: 'Getaway Shootout',
    slug: 'getaway-shootout',
    category: 'Action',
    ...cg('getaway-shootout'),
    rating: 4.4,
    playCount: 285000,
    description: 'Race to the getaway vehicle while shooting rivals out of the way. Crazy 2-player competitive fun!',
    featured: false,
    tags: ['2-player', 'shooting', 'race', 'funny'],
  },
  {
    title: 'Narrow One',
    slug: 'narrow-one',
    category: 'Action',
    ...cg('narrow-one'),
    rating: 4.5,
    playCount: 330000,
    description: 'A medieval archery multiplayer game with team-based capture-the-flag. Aim carefully and defend your flag.',
    featured: false,
    tags: ['archery', 'multiplayer', 'medieval', 'team'],
  },
  {
    title: 'Short Life',
    slug: 'short-life',
    category: 'Action',
    ...cg('short-life'),
    rating: 4.2,
    playCount: 210000,
    description: 'Guide a ragdoll character through brutal obstacle courses without losing any limbs. Hilariously violent fun!',
    featured: false,
    tags: ['ragdoll', 'obstacle', 'physics', 'funny'],
  },
  {
    title: 'Combat Online',
    slug: 'combat-online',
    category: 'Action',
    ...cg('combat-online'),
    rating: 4.1,
    playCount: 180000,
    description: 'Fast-paced online team combat. Pick your side and battle across multiple maps with various weapons.',
    featured: false,
    tags: ['action', 'multiplayer', 'combat', 'online'],
  },
  {
    title: 'Johnny Trigger',
    slug: 'johnny-trigger',
    category: 'Action',
    ...cg('johnny-trigger'),
    rating: 4.3,
    playCount: 265000,
    description: 'Shoot in stylish slow-motion action. Time your shots as Johnny leaps through action-movie scenes.',
    featured: false,
    tags: ['action', 'shooting', 'slow-motion', 'stylish'],
  },
  {
    title: 'EV.io',
    slug: 'ev-io',
    category: 'Action',
    ...cg('ev-io'),
    rating: 4.0,
    playCount: 155000,
    description: 'Sci-fi multiplayer FPS with fast movement and futuristic weapons. Jump around arenas and blast opponents.',
    featured: false,
    tags: ['fps', 'sci-fi', 'multiplayer', 'action'],
  },

  // ===== RACING (13 games) =====
  {
    title: 'Moto X3M',
    slug: 'moto-x3m',
    category: 'Racing',
    ...cg('moto-x3m'),
    rating: 4.7,
    playCount: 430000,
    description: 'Race your motorbike through challenging obstacle courses. Perform flips and stunts to earn extra points.',
    featured: true,
    tags: ['motorcycle', 'stunts', 'racing', 'physics'],
  },
  {
    title: 'Hill Climb Racing',
    slug: 'hill-climb-racing',
    category: 'Racing',
    ...cg('hill-climb-racing'),
    rating: 4.6,
    playCount: 290000,
    description: 'Drive over hills without flipping your vehicle. Upgrade cars and unlock new vehicles in this addictive physics racer.',
    featured: false,
    tags: ['driving', 'physics', 'racing', 'upgrade'],
  },
  {
    title: 'Drift Hunters',
    slug: 'drift-hunters',
    category: 'Racing',
    ...cg('drift-hunters'),
    rating: 4.7,
    playCount: 350000,
    description: 'Master the art of drifting in this realistic 3D driving game. Choose from tons of cars, tune them for maximum drift.',
    featured: true,
    tags: ['drifting', '3d', 'cars', 'racing'],
  },
  {
    title: 'Smash Karts',
    slug: 'smash-karts',
    category: 'Racing',
    ...cg('smash-karts'),
    rating: 4.6,
    playCount: 490000,
    description: 'Race around arenas in go-karts while collecting power-ups and blasting opponents. Fun multiplayer kart battle!',
    featured: true,
    tags: ['kart', 'multiplayer', 'battle', 'fun'],
  },
  {
    title: 'Madalin Cars Multiplayer',
    slug: 'madalin-cars-multiplayer',
    category: 'Racing',
    ...cg('madalin-cars-multiplayer'),
    rating: 4.5,
    playCount: 380000,
    description: 'Drive supercars on massive stunt tracks with ramps, loops, and jumps. Free-roam multiplayer mode!',
    featured: false,
    tags: ['supercars', 'stunts', 'multiplayer', '3d'],
  },
  {
    title: 'Moto X3M Pool Party',
    slug: 'moto-x3m-pool-party',
    category: 'Racing',
    ...cg('moto-x3m-pool-party'),
    rating: 4.6,
    playCount: 320000,
    description: 'Race motorbikes through wild pool party obstacle courses. More stunts, more water, more chaos!',
    featured: false,
    tags: ['motorcycle', 'stunts', 'pool', 'summer'],
  },
  {
    title: 'Death Chase',
    slug: 'death-chase',
    category: 'Racing',
    ...cg('death-chase'),
    rating: 4.3,
    playCount: 210000,
    description: 'Race through dangerous terrain performing insane stunts over bridges, cliffs and gaps.',
    featured: false,
    tags: ['stunts', '2-player', 'racing', 'extreme'],
  },
  {
    title: 'Burnout Drift',
    slug: 'burnout-drift',
    category: 'Racing',
    ...cg('burnout-drift'),
    rating: 4.4,
    playCount: 260000,
    description: 'Burn rubber and drift around corners. Customize your car, choose your track, and master controlled sliding.',
    featured: false,
    tags: ['drifting', 'cars', 'customization', '3d'],
  },
  {
    title: 'Moto X3M Spooky Land',
    slug: 'moto-x3m-spooky-land',
    category: 'Racing',
    ...cg('moto-x3m-spooky-land'),
    rating: 4.5,
    playCount: 290000,
    description: 'Halloween-themed Moto X3M with pumpkins, ghosts, and spooky obstacles. Race through haunted courses!',
    featured: false,
    tags: ['motorcycle', 'halloween', 'stunts', 'racing'],
  },
  {
    title: 'Snow Rider 3D',
    slug: 'snow-rider-3d',
    category: 'Racing',
    ...cg('snow-rider-3d'),
    rating: 4.5,
    playCount: 370000,
    description: 'Dodge trees and obstacles on an endless snowy slope. Collect gifts and set high scores on your sleigh!',
    featured: false,
    tags: ['snow', 'sledding', 'winter', 'casual'],
  },
  {
    title: 'Traffic Jam 3D',
    slug: 'traffic-jam-3d',
    category: 'Racing',
    ...cg('traffic-jam-3d'),
    rating: 4.0,
    playCount: 145000,
    description: 'Navigate intense 3D traffic on busy highway roads. Earn nitro boosts and unlock faster cars.',
    featured: false,
    tags: ['traffic', '3d', 'highway', 'speed'],
  },
  {
    title: 'Motocross Nitro',
    slug: 'motocross-nitro',
    category: 'Racing',
    ...cg('motocross-nitro'),
    rating: 4.2,
    playCount: 175000,
    description: 'Perform insane backflips and stunts in this motocross racing game. Land safely for huge nitro boosts.',
    featured: false,
    tags: ['motocross', 'stunts', 'nitro', 'racing'],
  },
  {
    title: 'Moto X3M 4',
    slug: 'moto-x3m-4',
    category: 'Racing',
    ...cg('moto-x3m-4'),
    rating: 4.1,
    playCount: 190000,
    description: 'The fourth installment of the insane Moto X3M series. New levels, new obstacles, same stunt-packed action.',
    featured: false,
    tags: ['motorcycle', 'stunts', 'obstacles', 'racing'],
  },

  // ===== PUZZLE (13 games) =====
  {
    title: 'Cut the Rope',
    slug: 'cut-the-rope',
    category: 'Puzzle',
    ...cg('cut-the-rope'),
    rating: 4.6,
    playCount: 320000,
    description: 'Feed Om Nom candy by cutting ropes in the right order. A classic physics-based puzzle game.',
    featured: true,
    tags: ['physics', 'puzzle', 'casual', 'brain'],
  },
  {
    title: '2048',
    slug: '2048',
    category: 'Puzzle',
    ...cg('2048'),
    rating: 4.4,
    playCount: 410000,
    description: 'Slide numbered tiles to combine them and reach 2048. Addictive math puzzle that challenges strategic thinking.',
    featured: false,
    tags: ['math', 'puzzle', 'numbers', 'brain'],
  },
  {
    title: 'Brain Puzzle',
    slug: 'brain-puzzle',
    category: 'Puzzle',
    ...cg('brain-puzzle'),
    rating: 4.5,
    playCount: 380000,
    description: 'Tricky riddles and brain teasers that challenge your thinking. Think outside the box to solve each level!',
    featured: false,
    tags: ['brain', 'riddles', 'tricky', 'iq'],
  },
  {
    title: 'Water Sort Puzzle',
    slug: 'water-sort-puzzle',
    category: 'Puzzle',
    ...cg('water-sort-puzzle'),
    rating: 4.4,
    playCount: 270000,
    description: 'Sort colored water between tubes until each tube contains only one color. Satisfying and relaxing!',
    featured: false,
    tags: ['sorting', 'colors', 'relaxing', 'logic'],
  },
  {
    title: 'Word Search',
    slug: 'word-search',
    category: 'Puzzle',
    ...cg('word-search'),
    rating: 4.7,
    playCount: 520000,
    description: 'Find hidden words in a grid of letters. Hundreds of puzzles across many themes and difficulty levels.',
    featured: true,
    tags: ['word', 'search', 'brain', 'letters'],
  },
  {
    title: 'Mahjong Classic',
    slug: 'mahjong-classic',
    category: 'Puzzle',
    ...cg('mahjong-classic'),
    rating: 4.3,
    playCount: 350000,
    description: 'Match pairs of identical tiles to clear the board. Hundreds of layouts to master in this classic game.',
    featured: false,
    tags: ['mahjong', 'matching', 'classic', 'tiles'],
  },
  {
    title: 'Tetrix',
    slug: 'tetrix',
    category: 'Puzzle',
    ...cg('tetrix'),
    rating: 4.6,
    playCount: 600000,
    description: 'The legendary block-stacking game. Rotate and place falling tetrominoes to complete lines.',
    featured: false,
    tags: ['blocks', 'classic', 'puzzle', 'retro'],
  },
  {
    title: 'Sudoku',
    slug: 'sudoku',
    category: 'Puzzle',
    ...cg('sudoku'),
    rating: 4.5,
    playCount: 280000,
    description: 'The world\'s most popular number puzzle. Fill the 9x9 grid so each row, column, and box contains 1-9.',
    featured: false,
    tags: ['sudoku', 'numbers', 'logic', 'classic'],
  },
  {
    title: 'Bubble Shooter',
    slug: 'bubble-shooter-classic',
    category: 'Puzzle',
    ...cg('bubble-shooter-classic'),
    rating: 4.3,
    playCount: 290000,
    description: 'Shoot colored bubbles and match 3 or more. Clear all bubbles before they reach the bottom.',
    featured: false,
    tags: ['bubble', 'shooter', 'match-3', 'casual'],
  },
  {
    title: 'Cut the Rope 2',
    slug: 'cut-the-rope-2',
    category: 'Puzzle',
    ...cg('cut-the-rope-2'),
    rating: 4.4,
    playCount: 310000,
    description: 'Feed Om Nom candy by cutting ropes and using new magical creatures. More levels, more physics fun!',
    featured: false,
    tags: ['physics', 'puzzle', 'casual', 'cute'],
  },
  {
    title: 'Minesweeper',
    slug: 'minesweeper',
    category: 'Puzzle',
    ...cg('minesweeper'),
    rating: 4.2,
    playCount: 220000,
    description: 'Clear the minefield using logic. Flag mines and reveal safe squares without triggering explosions.',
    featured: false,
    tags: ['minesweeper', 'logic', 'classic', 'deduction'],
  },
  {
    title: 'Hidden Object',
    slug: 'hidden-object',
    category: 'Puzzle',
    ...cg('hidden-object'),
    rating: 4.2,
    playCount: 190000,
    description: 'Find carefully hidden objects in beautifully illustrated scenes. Test your observation skills!',
    featured: false,
    tags: ['hidden', 'observation', 'relaxing', 'casual'],
  },
  {
    title: 'Adventure Capitalist',
    slug: 'adventure-capitalist',
    category: 'Puzzle',
    ...cg('adventure-capitalist'),
    rating: 4.3,
    playCount: 240000,
    description: 'Start with a lemonade stand and build a business empire. The ultimate idle clicker game!',
    featured: false,
    tags: ['idle', 'clicker', 'business', 'relaxing'],
  },

  // ===== SHOOTING (12 games) =====
  {
    title: 'Bullet Force',
    slug: 'bullet-force',
    category: 'Shooting',
    ...cg('bullet-force'),
    rating: 4.5,
    playCount: 285000,
    description: 'Action-packed multiplayer FPS with stunning 3D graphics. Customize your loadout and dominate.',
    featured: true,
    tags: ['fps', 'multiplayer', 'shooter', '3d'],
  },
  {
    title: 'Bullet Force',
    slug: 'bullet-force-multiplayer',
    category: 'Shooting',
    ...cg('bullet-force-multiplayer'),
    rating: 4.3,
    playCount: 260000,
    description: 'Online multiplayer FPS with customizable loadouts and multiple maps. Battle players worldwide!',
    featured: false,
    tags: ['fps', 'multiplayer', 'online', 'shooter'],
  },
  {
    title: 'Yohoho io',
    slug: 'yohoho-io',
    category: 'Shooting',
    ...cg('yohoho-io'),
    rating: 4.2,
    playCount: 220000,
    description: 'Pirate battle royale io game! Grow your pirate by defeating others and become the biggest one.',
    featured: false,
    tags: ['pirate', 'battle-royale', 'io', 'multiplayer'],
  },
  {
    title: 'Combat Reloaded',
    slug: 'combat-reloaded',
    category: 'Shooting',
    ...cg('combat-reloaded'),
    rating: 4.3,
    playCount: 215000,
    description: 'Team-based online FPS with multiple maps and modes. Fast-paced multiplayer shooting action.',
    featured: false,
    tags: ['fps', 'team', 'multiplayer', 'tactical'],
  },
  {
    title: '1v1.LOL',
    slug: '1v1-lol',
    category: 'Shooting',
    ...cg('1v1-lol'),
    rating: 4.4,
    playCount: 240000,
    description: 'Build structures and outshoot opponents in this competitive 1v1 battle game. Practice building and aiming.',
    featured: false,
    tags: ['building', '1v1', 'shooter', 'competitive'],
  },
  {
    title: 'Pixel Warfare',
    slug: 'pixel-warfare',
    category: 'Shooting',
    ...cg('pixel-warfare-5'),
    rating: 4.1,
    playCount: 195000,
    description: 'Blocky pixel-art FPS with multiple maps and weapons. Deathmatch, team fights, and survival modes.',
    featured: false,
    tags: ['pixel', 'fps', 'multiplayer', 'blocky'],
  },
  {
    title: 'Krunker io',
    slug: 'krunker-io',
    category: 'Shooting',
    ...cg('krunker'),
    rating: 4.5,
    playCount: 410000,
    description: 'Fast-paced browser FPS with pixel graphics. Choose your class and dominate the arena.',
    featured: false,
    tags: ['fps', 'io', 'multiplayer', 'pixel'],
  },
  {
    title: 'Gun Mayhem 2',
    slug: 'gun-mayhem-2',
    category: 'Shooting',
    ...cg('gun-mayhem-2'),
    rating: 4.4,
    playCount: 255000,
    description: 'Platform-style shooting game. Blast enemies off the stage with up to 4 players.',
    featured: false,
    tags: ['platform', '4-player', 'weapons', 'action'],
  },
  {
    title: 'Stick War',
    slug: 'stick-war',
    category: 'Shooting',
    ...cg('stick-war'),
    rating: 4.5,
    playCount: 340000,
    description: 'Command your stickman army in epic battles. Train units, mine gold, and destroy the enemy statue.',
    featured: false,
    tags: ['stickman', 'strategy', 'army', 'war'],
  },
  {
    title: 'Curve Fever Pro',
    slug: 'curve-fever-pro',
    category: 'Shooting',
    ...cg('curve-fever-pro'),
    rating: 4.2,
    playCount: 280000,
    description: 'Draw curves and trap opponents in this addictive multiplayer snake-battle game.',
    featured: false,
    tags: ['multiplayer', 'battle', 'snake', 'io'],
  },
  {
    title: 'Angry Birds',
    slug: 'angry-birds',
    category: 'Shooting',
    ...cg('angry-birds'),
    rating: 4.0,
    playCount: 150000,
    description: 'Launch birds from a slingshot to destroy pigs and their structures. The classic physics puzzler.',
    featured: false,
    tags: ['physics', 'slingshot', 'birds', 'classic'],
  },
  {
    title: 'Geometry Dash Meltdown',
    slug: 'geometry-dash-meltdown',
    category: 'Shooting',
    ...cg('geometry-dash-meltdown'),
    rating: 4.0,
    playCount: 175000,
    description: 'Race through danger in this free Geometry Dash spin-off. Jump, fly, and flip your way through the jungle.',
    featured: false,
    tags: ['rhythm', 'platformer', 'music', 'challenging'],
  },

  // ===== SPORTS (12 games) =====
  {
    title: 'Basketball Stars',
    slug: 'basketball-stars',
    category: 'Sports',
    ...cg('basketball-stars'),
    rating: 4.3,
    playCount: 195000,
    description: 'Fast-paced basketball 1v1. Show off your shooting skills and become the ultimate basketball star.',
    featured: true,
    tags: ['basketball', 'sports', 'multiplayer', '2-player'],
  },
  {
    title: 'Penalty Shooters 2',
    slug: 'penalty-shooters-2',
    category: 'Sports',
    ...cg('penalty-shooters-2'),
    rating: 4.3,
    playCount: 175000,
    description: 'Test your shooting and goalkeeping skills in the ultimate penalty shootout tournament.',
    featured: false,
    tags: ['football', 'soccer', 'sports', 'penalty'],
  },
  {
    title: 'Boxing Random',
    slug: 'boxing-random',
    category: 'Sports',
    ...cg('boxing-random'),
    rating: 4.3,
    playCount: 220000,
    description: 'Hilarious physics-based boxing where rules change every round. Random stages, random abilities!',
    featured: false,
    tags: ['boxing', 'physics', 'random', 'funny'],
  },
  {
    title: 'Tap Tap Shots',
    slug: 'tap-tap-shots',
    category: 'Sports',
    ...cg('tap-tap-shots'),
    rating: 4.2,
    playCount: 240000,
    description: 'Tap to shoot basketballs into the hoop. Time your taps perfectly to score big!',
    featured: false,
    tags: ['basketball', 'tap', 'reflex', 'casual'],
  },
  {
    title: 'Mini Golf Club',
    slug: 'mini-golf-club',
    category: 'Sports',
    ...cg('mini-golf-club'),
    rating: 4.4,
    playCount: 200000,
    description: 'Fun mini-golf with creative courses full of ramps, loops, and obstacles. Aim for a hole-in-one!',
    featured: false,
    tags: ['golf', 'mini-golf', 'multiplayer', 'casual'],
  },
  {
    title: 'Soccer Random',
    slug: 'soccer-random',
    category: 'Sports',
    ...cg('soccer-random'),
    rating: 4.4,
    playCount: 310000,
    description: 'Wild one-button soccer with randomly changing conditions and crazy physics. Utterly unpredictable!',
    featured: false,
    tags: ['soccer', 'random', 'funny', 'physics'],
  },
  {
    title: 'Basket Random',
    slug: 'basket-random',
    category: 'Sports',
    ...cg('basket-random'),
    rating: 4.3,
    playCount: 255000,
    description: 'Wacky basketball with random rule changes each round. Hilariously unpredictable 2-player action.',
    featured: false,
    tags: ['basketball', 'random', 'funny', '2-player'],
  },
  {
    title: 'Tennis Masters',
    slug: 'tennis-masters',
    category: 'Sports',
    ...cg('tennis-masters'),
    rating: 4.1,
    playCount: 140000,
    description: 'Compete in grand slam tennis tournaments. Master your serve and volley to become world number 1.',
    featured: false,
    tags: ['tennis', 'sports', 'tournament', 'competitive'],
  },
  {
    title: '8-Ball Billiards',
    slug: 'pool-party',
    category: 'Sports',
    ...cg('8-ball-billiards-classic'),
    rating: 4.3,
    playCount: 195000,
    description: 'Master 8-ball pool against AI opponents. Aim carefully and pot all your balls first.',
    featured: false,
    tags: ['pool', 'billiards', 'sports', 'skill'],
  },
  {
    title: 'Volley Random',
    slug: 'volley-random',
    category: 'Sports',
    ...cg('volley-random'),
    rating: 4.2,
    playCount: 185000,
    description: 'Crazy volleyball with physics that changes each round. A hilariously random sports experience.',
    featured: false,
    tags: ['volleyball', 'random', 'physics', 'funny'],
  },
  {
    title: 'Ping Pong',
    slug: 'ping-pong',
    category: 'Sports',
    ...cg('ping-pong'),
    rating: 4.0,
    playCount: 130000,
    description: 'Classic ping pong with realistic physics. Out-rally your opponent with spin and smart placement.',
    featured: false,
    tags: ['ping-pong', 'table-tennis', 'classic', 'sports'],
  },
  {
    title: 'Darts',
    slug: 'darts',
    category: 'Sports',
    ...cg('darts'),
    rating: 4.1,
    playCount: 155000,
    description: 'Throw darts at the board and hit bullseyes. Play solo or challenge a friend in classic 501 darts.',
    featured: false,
    tags: ['darts', 'aiming', 'precision', 'classic'],
  },

  // ===== ADVENTURE (12 games) =====
  {
    title: 'Fireboy and Watergirl',
    slug: 'fireboy-and-watergirl',
    category: 'Adventure',
    ...cg('fireboy-and-watergirl-the-forest-temple'),
    rating: 4.6,
    playCount: 440000,
    description: 'Team up to solve puzzles in the Forest Temple. Fireboy avoids water, Watergirl avoids fire — work together!',
    featured: true,
    tags: ['cooperative', '2-player', 'puzzle', 'adventure'],
  },
  {
    title: 'Fishing io',
    slug: 'fishing-io',
    category: 'Adventure',
    ...cg('fishing-io'),
    rating: 4.5,
    playCount: 560000,
    description: 'Catch fish and grow your boat in this multiplayer fishing io game. Battle other fishers on the open sea!',
    featured: true,
    tags: ['fishing', 'io', 'multiplayer', 'casual'],
  },
  {
    title: 'Minecraft Classic',
    slug: 'minecraft-classic',
    category: 'Adventure',
    ...cg('paper-minecraft'),
    rating: 4.8,
    playCount: 720000,
    description: 'Build and explore in the classic Minecraft. Place blocks, craft items, and create your own world.',
    featured: true,
    tags: ['sandbox', 'building', 'creative', 'multiplayer'],
  },
  {
    title: 'Bob the Robber',
    slug: 'bob-the-robber',
    category: 'Adventure',
    ...cg('bob-the-robber'),
    rating: 4.3,
    playCount: 280000,
    description: 'Sneak through buildings, avoid guards and cameras, and steal treasure. Stealth adventure with puzzles.',
    featured: false,
    tags: ['stealth', 'thief', 'puzzle', 'sneaking'],
  },
  {
    title: 'Paper io 2',
    slug: 'paper-io-2',
    category: 'Adventure',
    ...cg('paper-io-2'),
    rating: 4.2,
    playCount: 350000,
    description: 'Claim territory by drawing shapes. Protect your tail and invade other players\' areas.',
    featured: false,
    tags: ['io', 'territory', 'multiplayer', 'casual'],
  },
  {
    title: 'Raft Wars',
    slug: 'raft-wars',
    category: 'Adventure',
    ...cg('raft-wars'),
    rating: 4.4,
    playCount: 270000,
    description: 'Defend your hidden treasure from pirates by shooting from your raft. Knock them into the water!',
    featured: false,
    tags: ['pirate', 'shooting', 'aiming', 'funny'],
  },
  {
    title: 'Idle Breakout',
    slug: 'idle-breakout',
    category: 'Adventure',
    ...cg('idle-breakout'),
    rating: 4.3,
    playCount: 320000,
    description: 'Idle game meets brick breaker. Buy balls, upgrade them, and watch them destroy bricks automatically.',
    featured: false,
    tags: ['idle', 'clicker', 'breakout', 'relaxing'],
  },
  {
    title: 'Red Ball 4',
    slug: 'red-ball-4',
    category: 'Adventure',
    ...cg('red-ball-4'),
    rating: 4.5,
    playCount: 380000,
    description: 'Roll and jump through 75 levels as Red Ball. Defeat evil squares and save the round world!',
    featured: false,
    tags: ['platformer', 'physics', 'adventure', 'classic'],
  },
  {
    title: 'Snail Bob',
    slug: 'snail-bob',
    category: 'Adventure',
    ...cg('snail-bob'),
    rating: 4.2,
    playCount: 240000,
    description: 'Help Snail Bob navigate dangerous construction sites by clicking buttons and pulling levers.',
    featured: false,
    tags: ['point-and-click', 'puzzle', 'cute', 'adventure'],
  },
  {
    title: 'Dino Run',
    slug: 'dino-run',
    category: 'Adventure',
    ...cg('dino-run'),
    rating: 4.0,
    playCount: 230000,
    description: 'Run as a dinosaur through apocalyptic landscapes, jumping obstacles and collecting DNA to evolve.',
    featured: false,
    tags: ['dinosaur', 'running', 'survival', 'pixel'],
  },
  {
    title: 'Color Tunnel',
    slug: 'color-tunnel',
    category: 'Adventure',
    ...cg('color-tunnel'),
    rating: 4.2,
    playCount: 215000,
    description: 'Speed through a colorful tunnel maze. React fast and steer through glowing geometric obstacles.',
    featured: false,
    tags: ['tunnel', 'speed', 'reflex', 'colorful'],
  },
  {
    title: 'Run',
    slug: 'run',
    category: 'Adventure',
    ...cg('run'),
    rating: 4.1,
    playCount: 200000,
    description: 'Run through a tunnel in space, jumping over gaps and rotating the tunnel to survive.',
    featured: false,
    tags: ['runner', 'space', 'reflex', 'arcade'],
  },

  // ===== STRATEGY (13 games) =====
  {
    title: 'Chess',
    slug: 'chess',
    category: 'Strategy',
    ...cg('chess-free'),
    rating: 4.5,
    playCount: 310000,
    description: 'Classic chess against AI or a friend. Multiple difficulty levels to sharpen your tactical skills.',
    featured: false,
    tags: ['chess', 'strategy', 'board', 'classic'],
  },
  {
    title: 'Kingdom Rush',
    slug: 'kingdom-rush',
    category: 'Strategy',
    ...cg('kingdom-rush-frontiers'),
    rating: 4.7,
    playCount: 240000,
    description: 'Award-winning tower defense. Build towers, train soldiers, and use hero powers to protect the realm.',
    featured: true,
    tags: ['tower-defense', 'strategy', 'fantasy', 'medieval'],
  },
  {
    title: 'Bloons Tower Defense 5',
    slug: 'bloons-tower-defense-5',
    category: 'Strategy',
    ...cg('bloons-tower-defense-5'),
    rating: 4.7,
    playCount: 520000,
    description: 'Pop bloons with monkey towers. Strategically upgrade towers to survive endless waves.',
    featured: true,
    tags: ['tower-defense', 'monkeys', 'bloons', 'upgrade'],
  },
  {
    title: 'Age of War',
    slug: 'age-of-war',
    category: 'Strategy',
    ...cg('age-of-war'),
    rating: 4.4,
    playCount: 290000,
    description: 'Evolve through ages from cavemen to the future. Build units, defend your base, destroy the enemy.',
    featured: false,
    tags: ['evolution', 'base-defense', 'war', 'ages'],
  },
  {
    title: 'Plants vs Zombies',
    slug: 'plants-vs-zombies',
    category: 'Strategy',
    ...cg('plants-vs-zombies'),
    rating: 4.6,
    playCount: 450000,
    description: 'Defend your garden from zombies using plant warriors. Each plant has unique abilities.',
    featured: false,
    tags: ['tower-defense', 'zombies', 'plants', 'casual'],
  },
  {
    title: 'Bloons TD Battles',
    slug: 'bloons-td-battles',
    category: 'Strategy',
    ...cg('bit-heroes'),
    rating: 4.1,
    playCount: 170000,
    description: 'Epic idle RPG with dungeons, raids, and gear collection. Build your hero and conquer.',
    featured: false,
    tags: ['rpg', 'idle', 'dungeon', 'adventure'],
  },
  {
    title: 'Kingdom Rush Frontiers',
    slug: 'kingdom-rush-frontiers',
    category: 'Strategy',
    ...cg('kingdom-rush-frontiers'),
    rating: 4.3,
    playCount: 195000,
    description: 'Build powerful towers and stop enemies in this sequel to the award-winning tower defense game.',
    featured: false,
    tags: ['tower-defense', 'strategy', 'fantasy', 'upgrade'],
  },
  {
    title: 'Checkers',
    slug: 'checkers',
    category: 'Strategy',
    ...cg('checkers-online'),
    rating: 4.0,
    playCount: 160000,
    description: 'Classic checkers board game. Jump opponent pieces and king yours to dominate the board.',
    featured: false,
    tags: ['checkers', 'board', 'classic', '2-player'],
  },
  {
    title: 'Minesweeper',
    slug: 'minesweeper',
    category: 'Strategy',
    ...cg('minesweeper'),
    rating: 4.2,
    playCount: 175000,
    description: 'Clear the minefield using logic. Flag mines and reveal safe squares without triggering explosions.',
    featured: false,
    tags: ['minesweeper', 'logic', 'classic', 'deduction'],
  },
  {
    title: 'Tic Tac Toe',
    slug: 'tic-tac-toe',
    category: 'Strategy',
    ...cg('tic-tac-toe'),
    rating: 4.0,
    playCount: 200000,
    description: 'The classic X and O game. Play against a smart AI or challenge a friend to tic-tac-toe.',
    featured: false,
    tags: ['tic-tac-toe', 'classic', 'board', '2-player'],
  },
  {
    title: 'Solitaire Classic',
    slug: 'solitaire-classic',
    category: 'Strategy',
    ...cg('classic-solitaire'),
    rating: 4.3,
    playCount: 280000,
    description: 'The timeless card game — Klondike Solitaire. Sort cards into foundations and beat the deck!',
    featured: false,
    tags: ['solitaire', 'cards', 'classic', 'relaxing'],
  },
  {
    title: 'Factory Idle',
    slug: 'factory-idle',
    category: 'Strategy',
    ...cg('factory-idle'),
    rating: 4.2,
    playCount: 175000,
    description: 'Build and optimize factories to maximize production. A deeply satisfying idle management game.',
    featured: false,
    tags: ['idle', 'factory', 'management', 'clicker'],
  },
  {
    title: 'Mini Putt',
    slug: 'mini-putt',
    category: 'Strategy',
    ...cg('mini-putt'),
    rating: 4.1,
    playCount: 130000,
    description: 'Classic mini golf game with tricky courses. Aim carefully and sink the ball in as few shots as possible.',
    featured: false,
    tags: ['mini-golf', 'golf', 'skill', 'classic'],
  },

  // ===== ARCADE (12 games) =====
  {
    title: 'Geometry Dash',
    slug: 'geometry-dash',
    category: 'Arcade',
    ...cg('geometry-dash-meltdown'),
    rating: 4.6,
    playCount: 490000,
    description: 'Rhythm-based action platformer. Push your skills to the limit on levels synced to electronic music.',
    featured: true,
    tags: ['rhythm', 'platformer', 'music', 'challenging'],
  },
  {
    title: 'Tunnel Rush',
    slug: 'tunnel-rush',
    category: 'Arcade',
    ...cg('tunnel-rush'),
    rating: 4.3,
    playCount: 270000,
    description: 'Navigate through a colorful tunnel at high speed, dodging obstacles. Test your reflexes!',
    featured: false,
    tags: ['reflex', 'speed', '3d', 'arcade'],
  },
  {
    title: 'Snake io',
    slug: 'snake-io',
    category: 'Arcade',
    ...cg('snake-io'),
    rating: 4.1,
    playCount: 180000,
    description: 'Grow your snake by eating orbs and outmaneuver opponents. Become the biggest snake!',
    featured: false,
    tags: ['io', 'snake', 'multiplayer', 'casual'],
  },
  {
    title: 'Fruit Ninja',
    slug: 'fruit-ninja',
    category: 'Arcade',
    ...cg('fruit-ninja'),
    rating: 4.2,
    playCount: 210000,
    description: 'Slice fruit like a true ninja! Watch out for bombs and aim for combos and high scores.',
    featured: false,
    tags: ['casual', 'arcade', 'slicing', 'reflex'],
  },
  {
    title: 'Crossy Road',
    slug: 'crossy-road',
    category: 'Arcade',
    ...cg('crossy-road'),
    rating: 4.4,
    playCount: 325000,
    description: 'Hop through traffic, rivers, and train tracks in this endless arcade hopper.',
    featured: false,
    tags: ['arcade', 'endless', 'casual', 'pixel'],
  },
  {
    title: 'Helix Jump',
    slug: 'helix-jump',
    category: 'Arcade',
    ...cg('helix-jump'),
    rating: 4.3,
    playCount: 340000,
    description: 'Bounce your ball down through a rotating helix tower. Avoid colored platforms and reach the bottom.',
    featured: false,
    tags: ['bouncing', '3d', 'casual', 'satisfying'],
  },
  {
    title: 'Agar io',
    slug: 'agar-io',
    category: 'Arcade',
    ...cg('agario'),
    rating: 4.3,
    playCount: 480000,
    description: 'Grow your cell by eating smaller ones and avoid being eaten by larger cells. Classic io game!',
    featured: false,
    tags: ['io', 'multiplayer', 'classic', 'grow'],
  },
  {
    title: 'Slither io',
    slug: 'slither-io',
    category: 'Arcade',
    ...cg('slitherio'),
    rating: 4.4,
    playCount: 560000,
    description: 'Grow your snake by eating glowing orbs. Trap other snakes to collect their mass.',
    featured: false,
    tags: ['io', 'snake', 'multiplayer', 'competitive'],
  },
  {
    title: 'Worm Hunt',
    slug: 'worm-hunt',
    category: 'Arcade',
    ...cg('worm-hunt'),
    rating: 4.2,
    playCount: 290000,
    description: 'Grow your worm by eating dots and defeating others. Classic snake-style io action with power-ups!',
    featured: false,
    tags: ['io', 'snake', 'multiplayer', 'grow'],
  },
  {
    title: 'Dino Run',
    slug: 'dino-run-arcade',
    category: 'Arcade',
    ...cg('dino-run'),
    rating: 4.2,
    playCount: 265000,
    description: 'Race a pixel dinosaur from an apocalyptic eruption. Eat other creatures to survive longer!',
    featured: false,
    tags: ['dinosaur', 'survival', 'pixel', 'runner'],
  },
  {
    title: 'Eggy Car',
    slug: 'eggy-car-arcade',
    category: 'Arcade',
    ...cg('eggy-car'),
    rating: 4.1,
    playCount: 200000,
    description: 'Balance an egg on your car while driving over hills without dropping it. Hilarious physics fun!',
    featured: false,
    tags: ['physics', 'driving', 'casual', 'balance'],
  },
  {
    title: 'Flappy Bird',
    slug: 'flappy-bird',
    category: 'Arcade',
    ...cg('flappy-bird'),
    rating: 4.0,
    playCount: 550000,
    description: 'Tap to flap through pipes. The infamously difficult game that took the world by storm.',
    featured: false,
    tags: ['flappy', 'challenging', 'tap', 'addictive'],
  },
];
